###########################################################
# Examine Data output from distance modeling. 
# Create unified dataframe of original data and new data estimates 
###########################################################
# Load Packages --------------------------------------------------------------
library(tidyverse)

###########################################################
# Set WD --------------------------------------------------------------
setwd("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistanceModel_Test/Models")

###########################################################
# Load Data --------------------------------------------------------------
df<- read.csv("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistanceModel_Test/birds2017_AllPlotTypes_B2_FirstCount_SpeciesRank_NoNoct_250Distance_NoOverlap_covariateReconstruct.csv", header = T) # Code ready 2017 count data with covariates (filtered)

# Load  Super computer data
MultiSp_FullModel_Super <- readRDS("/Users/colinsweeney/Documents/Documents/PhD/SuperComputer/Chapter1_DistSample/output/20000/MultiSp_DistModel_2017_20000run.rds")

df_super<- as.data.frame(MultiSp_FullModel_Super$mean$N)
df_super<- tibble::rownames_to_column(df_super, "plotNum") # convert rows to columns
model_output <- df_super

# Export just the mean N values ------------------------------------------
write_csv(model_output, "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistModel_Final/outputs/N_output_20000_super.csv")
#model_output <- read.csv("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistModel_Final/outputs/N_output_20000_super.csv")

################################################################################
# Tidy up original data frame to get it ready for data merge -------------------
df<- df%>% dplyr::filter(taxonRank == "species") # Filter out TOOL_007 (which has had 1 species but no distance information)
df <- df%>%dplyr::mutate(domainID = domainID.y, siteID= siteID.y, pointID= pointID.y)

# Clean up NA Data
df <- df%>%dplyr::filter(!is.na(startCloudCoverPercentage)) # filter out cloud cover NAs 
df <- df%>%dplyr::filter(!is.na(kmPerHourObservedWindSpeed))
df <- df%>%dplyr::filter(!is.na(observedAirTemp))
df <- df%>%dplyr::filter(!is.na(elevation)) # filter out elevation NAs 

df$plotNum <- as.numeric(as.factor(df$plotID)) #create new column to hold numeric site IDs: needed for Kery and Royle code (can't take non-numeric reference data)

df$spec <- as.numeric(as.factor(df$scientificName)) #create new column to hold numeric site IDs: needed for Kery and Royle code (can't take non-numeric reference data)

df <- dplyr::select(df, plotNum, domainID, siteID, plotID, year, month, day, pointCountMinute, taxonRank, taxonID, scientificName, vernacularName, spec, observerDistance, detectionMethod, visualConfirmation, sexOrAge, clusterSize, identifiedBy, nlcdClass, decimalLatitude, decimalLongitude, elevation, startCloudCoverPercentage, endCloudCoverPercentage, startRH, endRH, observedHabitat, observedAirTemp, kmPerHourObservedWindSpeed) # filter out extra columns. 

df$observerDistance <- df$observerDistance/1000 # convert to km

summary(df$plotNum) 
sum(df$clusterSize)

######################
#### IN PROGRESS #########
# Repeat cluster size rows so that they can sum up normally. 
cs_2 <-df %>% filter(clusterSize==2)
cs_3 <-df %>% filter(clusterSize==3)
cs_4 <-df %>% filter(clusterSize==4)
cs_5 <-df %>% filter(clusterSize==5)
cs_6 <-df %>% filter(clusterSize==6)
cs_7 <-df %>% filter(clusterSize==7)
cs_9 <-df %>% filter(clusterSize==9)
cs_12 <-df %>% filter(clusterSize==12)
cs_16 <-df %>% filter(clusterSize==16)
cs_20 <-df %>% filter(clusterSize==20)

# df <- rbind(df,cs_2, cs_3, cs_3) # now there are repeat rows for cluster size of 2 and 3
df <- rbind(df,cs_2, cs_3, cs_3, cs_4, cs_4, cs_4, cs_5, cs_5, cs_5, cs_5, cs_6, cs_6, cs_6, cs_6, cs_6, cs_7, cs_7, cs_7, cs_7, cs_7, cs_7, cs_9, cs_9, cs_9, cs_9, cs_9, cs_9, cs_9, cs_9, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_12, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_16, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20, cs_20)

df$clusterSize <- 1 # asign all clusterSize to 1 since rows are now repeated. 
table(df$clusterSize)

df <- df%>%arrange(plotNum, spec, observerDistance) # arrange table so it's in a standard order

############ create data matrix in R directly since there are now apparently issues with excel pivot tables. 
# subset needed columns
# blah <- df[,c("plotID","scientificName","clusterSize")]
blah <- df[,c("plotNum","spec","clusterSize")] 

Key <- df[,c("spec","scientificName", "vernacularName")]%>% arrange(spec) %>%unique()

# create pivot table of plotID vs scientificName, summarizing clusterSize
# blah2 <- blah %>% group_by(plotID, scientificName)%>% summarize(clusterSize = n()) %>% ungroup() %>% as.data.frame() %>% pivot_wider(names_from = scientificName, values_from = clusterSize)

# blah2 <- blah %>% group_by(plotNum, spec)%>% summarize(clusterSize = n()) %>% ungroup() %>% as.data.frame() %>% pivot_wider(names_from = spec, values_from = clusterSize)

blah2 <- blah %>% group_by(plotNum, spec)%>% summarize(clusterSize = n()) %>% ungroup() %>% as.data.frame() %>% arrange(spec) %>% pivot_wider(names_from = spec, values_from = clusterSize)

blah2[is.na(blah2)] = 0 # asign zeros to all "NA" 
blah2 # check 
blah2<- blah2%>%arrange(plotNum) # put the plotNum in order

blah2<-as.data.frame(blah2)
row.names(blah2)<- blah2$plotID

colnames(blah2) <- c("plotNum", Key$scientificName) # rename column names to be scientific names

View(Key) # key for spec and scientific names 

################################################################################
# write_csv(as.data.frame(y), "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DataPrep/InputData/2017_NEON_bird_inputdata.csv")

# write_csv(as.data.frame(blah2), "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DataPrep/InputData/2017_NEON_bird_inputdata_blah2.csv")

# write_csv(df, "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DataPrep/InputData/2017_NEON_bird_inputdata_df.csv")

# model_output <- read.csv("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistanceModel_Test/Outputs/N_output_10000_test_labels.csv")

################################################################################
blah2 # original abundance data for each species by plotNum
model_output # dist model corrected abundances for each species by plotNum

library(plyr)
spRich_original <- ddply(blah2,~plotNum,function(x) {data.frame(Original_RICHNESS=sum(x[-1]>0))})
spRich_discorr <- ddply(model_output,~plotNum,function(x) {data.frame(distcorr_RICHNESS=sum(x[-1]>1))})

spRich_combined <-spRich_original%>% right_join(spRich_discorr, by = "plotNum")
length(spRich_combined$plotNum)
summary(spRich_combined)

plot(spRich_combined$Original_RICHNESS, spRich_combined$distcorr_RICHNESS, xlim =c(0,50), ylim=c(0,50), ylab="Dist Corrected spRich", xlab="Original spRich")
abline(coef=c(0,1))

hist(spRich_combined$distcorr_RICHNESS,col='red')
hist(spRich_combined$Original_RICHNESS,col='green',add=TRUE)


######
###############################################################################
model_output[model_output<1] <- NA # convert all decimal values to zero
blah2[blah2==0]<-NA
###############################################################################
######
test <- df%>% right_join(blah2, by = "plotNum")
test2 <- test%>%right_join(model_output, by="plotNum")

View(test2)

write_csv(test2, "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistModel_Final/Plots/20000_super_rangemap_original_distcorrect_plotting_test2.csv")

test2 <- read.csv("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistModel_Final/Plots/20000_super_rangemap_original_distcorrect_plotting_test2.csv")
# write_csv(as.data.frame(test2), "/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistanceModel_Test/Outputs/2017_NEON_bird_inputANDoutput_test2.csv")

####### Read file back in for the sake of plotting ############################
# test2<- read.csv("/Users/colinsweeney/Documents/Documents/PhD/Chapter1/2017_DistanceModel_Test/Outputs/2017_NEON_bird_inputANDoutput_test2.csv")


###############################################################################
#### Plot the scatter plot of before and after with a 1:1 relationship slope
par(mfrow = c(1, 1))
plot(test2$`Acanthis flammea`, test2$V1)
abline(coef=c(0,1))

# See the range of the data for xlim, ylim purposes
# View(summary(test2[,31:290]))
# View(summary(test2[,291:550]))
# View(pmax(summary(test2[,291:550])))
# thing <- pmax(summary(test2[,291:550]))
####
# plot(x, y, xlim =40, ylim=40)
# abline(coef=c(0,1))

# Takes a while to plot 
plot(test2$`Acanthis flammea`, test2$V1, xlim =c(0,20), ylim=c(0,120), ylab="Dist Corrected Abundance", xlab="Original Abundance")

points(test2$`Accipiter cooperii`, test2$V2)
points(test2$`Agelaius phoeniceus`, test2$V3)
points(test2$`Aimophila ruficeps`, test2$V4)
points(test2$`Aix sponsa`, test2$V5)
points(test2$`Ammodramus henslowii`, test2$V6)
points(test2$`Ammodramus savannarum`, test2$V7)
points(test2$`Amphispiza bilineata`, test2$V8)
points(test2$`Anas americana`, test2$V9)
points(test2$`Anas discors`, test2$V10)
points(test2$`Anas platyrhynchos`, test2$V11)
points(test2$`Anthus rubescens`, test2$V12)
points(test2$`Aphelocoma californica`, test2$V13)
points(test2$`Archilochus alexandri`, test2$V14)
points(test2$`Archilochus colubris`, test2$V15)
points(test2$`Ardea alba`, test2$V16)
points(test2$`Ardea herodias`, test2$V17)
points(test2$`Auriparus flaviceps`, test2$V18)
points(test2$`Aythya affinis`, test2$V19)
points(test2$`Aythya americana`, test2$V20)
points(test2$`Baeolophus bicolor`, test2$V21)
points(test2$`Baeolophus inornatus`, test2$V22)
points(test2$`Baeolophus ridgwayi`, test2$V23)
points(test2$`Bartramia longicauda`, test2$V24)
points(test2$`Bombycilla cedrorum`, test2$V25)
points(test2$`Bonasa umbellus`, test2$V26)
points(test2$`Branta canadensis`, test2$V27)
points(test2$`Bubulcus ibis`, test2$V28)
points(test2$`Buteo jamaicensis`, test2$V29)
points(test2$`Buteo lineatus`, test2$V30)
points(test2$`Buteo platypterus`, test2$V31)
points(test2$`Calamospiza melanocorys`, test2$V32)
points(test2$`Calcarius lapponicus`, test2$V33)
points(test2$`Calcarius pictus`, test2$V34)
points(test2$`Calidris alpina`, test2$V35)
points(test2$`Calidris melanotos`, test2$V36)
points(test2$`Calidris pusilla`, test2$V37)
points(test2$`Callipepla californica`, test2$V38)
points(test2$`Callipepla gambelii`, test2$V39)
points(test2$`Callipepla squamata`, test2$V40)
points(test2$`Calypte anna`, test2$V41)
points(test2$`Campylorhynchus brunneicapillus`, test2$V42)
points(test2$`Cardellina pusilla`, test2$V43)
points(test2$`Cardinalis cardinalis`, test2$V44)
points(test2$`Cardinalis sinuatus`, test2$V45)
points(test2$`Cathartes aura`, test2$V46)
points(test2$`Catharus fuscescens`, test2$V47)
points(test2$`Catharus guttatus`, test2$V48)
points(test2$`Catharus minimus`, test2$V49)
points(test2$`Catharus ustulatus`, test2$V50)
points(test2$`Catherpes mexicanus`, test2$V51)
points(test2$`Certhia americana`, test2$V52)
points(test2$`Chaetura pelagica`, test2$V53)
points(test2$`Chamaea fasciata`, test2$V54)
points(test2$`Charadrius vociferus`, test2$V55)
points(test2$`Chlidonias niger`, test2$V56)
points(test2$`Chondestes grammacus`, test2$V57)
points(test2$`Circus cyaneus`, test2$V58)
points(test2$`Cistothorus palustris`, test2$V59)
points(test2$`Cistothorus platensis`, test2$V60)
points(test2$`Clangula hyemalis`, test2$V61)
points(test2$`Coccyzus americanus`, test2$V62)
points(test2$`Colaptes auratus`, test2$V63)
points(test2$`Colaptes chrysoides`, test2$V64)
points(test2$`Colinus virginianus`, test2$V65)
points(test2$`Columbina passerina`, test2$V66)
points(test2$`Contopus cooperi`, test2$V67)
points(test2$`Contopus sordidulus`, test2$V68)
points(test2$`Contopus virens`, test2$V69)
points(test2$`Corvus brachyrhynchos`, test2$V70)
points(test2$`Corvus corax`, test2$V71)
points(test2$`Corvus cryptoleucus`, test2$V72)
points(test2$`Corvus ossifragus`, test2$V73)
points(test2$`Cyanocitta cristata`, test2$V74)
points(test2$`Cyanocitta stelleri`, test2$V75)
points(test2$`Dolichonyx oryzivorus`, test2$V76)
points(test2$`Dryocopus pileatus`, test2$V77)
points(test2$`Dumetella carolinensis`, test2$V78)
points(test2$`Empidonax alnorum`, test2$V79)
points(test2$`Empidonax difficilis`, test2$V80)
points(test2$`Empidonax hammondii`, test2$V81)
points(test2$`Empidonax minimus`, test2$V82)
points(test2$`Empidonax oberholseri`, test2$V83)
points(test2$`Empidonax occidentalis`, test2$V84)
points(test2$`Empidonax traillii`, test2$V85)
points(test2$`Empidonax virescens`, test2$V86)
points(test2$`Empidonax wrightii`, test2$V87)
points(test2$`Eremophila alpestris`, test2$V88)
points(test2$`Eudocimus albus`, test2$V89)
points(test2$`Euphagus cyanocephalus`, test2$V90)
points(test2$`Falco sparverius`, test2$V91)
points(test2$`Gavia pacifica`, test2$V92)
points(test2$`Geococcyx californianus`, test2$V93)
points(test2$`Geothlypis formosa`, test2$V94)
points(test2$`Geothlypis philadelphia`, test2$V95)
points(test2$`Geothlypis tolmiei`, test2$V96)
points(test2$`Geothlypis trichas`, test2$V97)
points(test2$`Grus canadensis`, test2$V98)
points(test2$`Haemorhous cassinii`, test2$V99)
points(test2$`Haemorhous mexicanus`, test2$V100)
points(test2$`Haemorhous purpureus`, test2$V101)
points(test2$`Helmitheros vermivorum`, test2$V102)
points(test2$`Hirundo rustica`, test2$V103)
points(test2$`Hylocichla mustelina`, test2$V104)
points(test2$`Icteria virens`, test2$V105)
points(test2$`Icterus bullockii`, test2$V106)
points(test2$`Icterus galbula`, test2$V107)
points(test2$`Icterus parisorum`, test2$V108)
points(test2$`Icterus spurius`, test2$V109)
points(test2$`Ixoreus naevius`, test2$V110)
points(test2$`Junco hyemalis`, test2$V111)
points(test2$`Lanius ludovicianus`, test2$V112)
points(test2$`Larus delawarensis`, test2$V113)
points(test2$`Larus hyperboreus`, test2$V114)
points(test2$`Limnothlypis swainsonii`, test2$V115)
points(test2$`Loxia curvirostra`, test2$V116)
points(test2$`Loxia leucoptera`, test2$V117)
points(test2$`Melanerpes carolinus`, test2$V118)
points(test2$`Melanerpes erythrocephalus`, test2$V119)
points(test2$`Melanerpes formicivorus`, test2$V120)
points(test2$`Melanerpes uropygialis`, test2$V121)
points(test2$`Meleagris gallopavo`, test2$V122)
points(test2$`Melospiza georgiana`, test2$V123)
points(test2$`Melospiza lincolnii`, test2$V124)
points(test2$`Melospiza melodia`, test2$V125)
points(test2$`Melozone crissalis`, test2$V126)
points(test2$`Mimus polyglottos`, test2$V127)
points(test2$`Mniotilta varia`, test2$V128)
points(test2$`Molothrus ater`, test2$V129)
points(test2$`Myadestes townsendi`, test2$V130)
points(test2$`Myiarchus cinerascens`, test2$V131)
points(test2$`Myiarchus crinitus`, test2$V132)
points(test2$`Nucifraga columbiana`, test2$V133)
points(test2$`Numenius phaeopus`, test2$V134)
points(test2$`Nycticorax nycticorax`, test2$V135)
points(test2$`Oreoscoptes montanus`, test2$V136)
points(test2$`Parkesia motacilla`, test2$V137)
points(test2$`Passer domesticus`, test2$V138)
points(test2$`Passerculus sandwichensis`, test2$V139)
points(test2$`Passerella iliaca`, test2$V140)
points(test2$`Passerina amoena`, test2$V141)
points(test2$`Passerina caerulea`, test2$V142)
points(test2$`Passerina ciris`, test2$V143)
points(test2$`Passerina cyanea`, test2$V144)
points(test2$`Pelecanus erythrorhynchos`, test2$V145)
points(test2$`Perisoreus canadensis`, test2$V146)
points(test2$`Petrochelidon pyrrhonota`, test2$V147)
points(test2$`Peucaea aestivalis`, test2$V148)
points(test2$`Peucaea botterii`, test2$V149)
points(test2$`Peucaea carpalis`, test2$V150)
points(test2$`Peucaea cassinii`, test2$V151)
points(test2$`Phainopepla nitens`, test2$V152)
points(test2$`Phalacrocorax auritus`, test2$V153)
points(test2$`Phalaropus fulicarius`, test2$V154)
points(test2$`Phalaropus tricolor`, test2$V155)
points(test2$`Phasianus colchicus`, test2$V156)
points(test2$`Pheucticus ludovicianus`, test2$V157)
points(test2$`Pheucticus melanocephalus`, test2$V158)
points(test2$`Pica hudsonia`, test2$V159)
points(test2$`Picoides albolarvatus`, test2$V160)
points(test2$`Picoides nuttallii`, test2$V161)
points(test2$`Picoides scalaris`, test2$V162)
points(test2$`Picoides villosus`, test2$V163)
points(test2$`Pinicola enucleator`, test2$V164)
points(test2$`Pipilo chlorurus`, test2$V165)
points(test2$`Pipilo erythrophthalmus`, test2$V166)
points(test2$`Pipilo maculatus`, test2$V167)
points(test2$`Piranga ludoviciana`, test2$V168)
points(test2$`Piranga olivacea`, test2$V169)
points(test2$`Piranga rubra`, test2$V170)
points(test2$`Plectrophenax nivalis`, test2$V171)
points(test2$`Pluvialis dominica`, test2$V172)
points(test2$`Poecile atricapillus`, test2$V173)
points(test2$`Poecile gambeli`, test2$V174)
points(test2$`Poecile hudsonicus`, test2$V175)
points(test2$`Polioptila caerulea`, test2$V176)
points(test2$`Polioptila melanura`, test2$V177)
points(test2$`Porzana carolina`, test2$V178)
points(test2$`Progne subis`, test2$V179)
points(test2$`Protonotaria citrea`, test2$V180)
points(test2$`Psaltriparus minimus`, test2$V181)
points(test2$`Pyrocephalus rubinus`, test2$V182)
points(test2$`Quiscalus major`, test2$V183)
points(test2$`Quiscalus quiscula`, test2$V184)
points(test2$`Rallus limicola`, test2$V185)
points(test2$`Regulus calendula`, test2$V186)
points(test2$`Regulus satrapa`, test2$V187)
points(test2$`Sayornis nigricans`, test2$V188)
points(test2$`Sayornis phoebe`, test2$V189)
points(test2$`Seiurus aurocapilla`, test2$V190)
points(test2$`Selasphorus platycercus`, test2$V191)
points(test2$`Selasphorus rufus`, test2$V192)
points(test2$`Setophaga caerulescens`, test2$V193)
points(test2$`Setophaga citrina`, test2$V194)
points(test2$`Setophaga coronata`, test2$V195)
points(test2$`Setophaga discolor`, test2$V196)
points(test2$`Setophaga dominica`, test2$V197)
points(test2$`Setophaga fusca`, test2$V198)
points(test2$`Setophaga magnolia`, test2$V199)
points(test2$`Setophaga nigrescens`, test2$V200)
points(test2$`Setophaga occidentalis`, test2$V201)
points(test2$`Setophaga pensylvanica`, test2$V202)
points(test2$`Setophaga petechia`, test2$V203)
points(test2$`Setophaga pinus`, test2$V204)
points(test2$`Setophaga ruticilla`, test2$V205)
points(test2$`Setophaga striata`, test2$V206)
points(test2$`Setophaga virens`, test2$V207)
points(test2$`Sialia currucoides`, test2$V208)
points(test2$`Sialia mexicana`, test2$V209)
points(test2$`Sialia sialis`, test2$V210)
points(test2$`Sitta canadensis`, test2$V211)
points(test2$`Sitta carolinensis`, test2$V212)
points(test2$`Sitta pusilla`, test2$V213)
points(test2$`Sitta pygmaea`, test2$V214)
points(test2$`Sphyrapicus ruber`, test2$V215)
points(test2$`Sphyrapicus varius`, test2$V216)
points(test2$`Spinus lawrencei`, test2$V217)
points(test2$`Spinus pinus`, test2$V218)
points(test2$`Spinus psaltria`, test2$V219)
points(test2$`Spinus tristis`, test2$V220)
points(test2$`Spiza americana`, test2$V221)
points(test2$`Spizella breweri`, test2$V222)
points(test2$`Spizella pallida`, test2$V223)
points(test2$`Spizella passerina`, test2$V224)
points(test2$`Spizella pusilla`, test2$V225)
points(test2$`Spizelloides arborea`, test2$V226)
points(test2$`Stercorarius longicaudus`, test2$V227)
points(test2$`Stercorarius parasiticus`, test2$V228)
points(test2$`Sturnella magna`, test2$V229)
points(test2$`Sturnella neglecta`, test2$V230)
points(test2$`Sturnus vulgaris`, test2$V231)
points(test2$`Tachycineta bicolor`, test2$V232)
points(test2$`Tachycineta thalassina`, test2$V233)
points(test2$`Thryomanes bewickii`, test2$V234)
points(test2$`Thryothorus ludovicianus`, test2$V235)
points(test2$`Toxostoma crissale`, test2$V236)
points(test2$`Toxostoma curvirostre`, test2$V237)
points(test2$`Toxostoma rufum`, test2$V238)
points(test2$`Troglodytes aedon`, test2$V239)
points(test2$`Turdus migratorius`, test2$V240)
points(test2$`Tyrannus forficatus`, test2$V241)
points(test2$`Tyrannus tyrannus`, test2$V242)
points(test2$`Tyrannus verticalis`, test2$V243)
points(test2$`Tyrannus vociferans`, test2$V244)
points(test2$`Vireo bellii`, test2$V245)
points(test2$`Vireo cassinii`, test2$V246)
points(test2$`Vireo flavifrons`, test2$V247)
points(test2$`Vireo gilvus`, test2$V248)
points(test2$`Vireo griseus`, test2$V249)
points(test2$`Vireo huttoni`, test2$V250)
points(test2$`Vireo olivaceus`, test2$V251)
points(test2$`Vireo plumbeus`, test2$V252)
points(test2$`Vireo solitarius`, test2$V253)
points(test2$`Vireo vicinior`, test2$V254)
points(test2$`Xanthocephalus xanthocephalus`, test2$V255)
points(test2$`Zenaida asiatica`, test2$V256)
points(test2$`Zenaida macroura`, test2$V257)
points(test2$`Zonotrichia albicollis`, test2$V258)
points(test2$`Zonotrichia atricapilla`, test2$V259)
points(test2$`Zonotrichia leucophrys`, test2$V260)
abline(coef=c(0,1))


####
plot(test2$`Acanthis flammea`, test2$V1) 
abline(coef=c(0,1))
plot(test2$`Accipiter cooperii`, test2$V2) 
abline(coef=c(0,1))
plot(test2$`Agelaius phoeniceus`, test2$V3) 
abline(coef=c(0,1))
plot(test2$`Aimophila ruficeps`, test2$V4) 
abline(coef=c(0,1))
plot(test2$`Aix sponsa`, test2$V5) 
abline(coef=c(0,1))
plot(test2$`Ammodramus henslowii`, test2$V6) 
abline(coef=c(0,1))
plot(test2$`Ammodramus savannarum`, test2$V7) 
abline(coef=c(0,1))
plot(test2$`Amphispiza bilineata`, test2$V8) 
abline(coef=c(0,1))
plot(test2$`Anas americana`, test2$V9) 
abline(coef=c(0,1))
plot(test2$`Anas discors`, test2$V10) 
abline(coef=c(0,1))
plot(test2$`Anas platyrhynchos`, test2$V11) 
abline(coef=c(0,1))
plot(test2$`Anthus rubescens`, test2$V12) 
abline(coef=c(0,1))
plot(test2$`Aphelocoma californica`, test2$V13) 
abline(coef=c(0,1))
plot(test2$`Archilochus alexandri`, test2$V14) 
abline(coef=c(0,1))
plot(test2$`Archilochus colubris`, test2$V15) 
abline(coef=c(0,1))
plot(test2$`Ardea alba`, test2$V16) 
abline(coef=c(0,1))
plot(test2$`Ardea herodias`, test2$V17) 
abline(coef=c(0,1))
plot(test2$`Auriparus flaviceps`, test2$V18) 
abline(coef=c(0,1))
plot(test2$`Aythya affinis`, test2$V19) 
abline(coef=c(0,1))
plot(test2$`Aythya americana`, test2$V20) 
abline(coef=c(0,1))
plot(test2$`Baeolophus bicolor`, test2$V21) 
abline(coef=c(0,1))
plot(test2$`Baeolophus inornatus`, test2$V22) 
abline(coef=c(0,1))
plot(test2$`Baeolophus ridgwayi`, test2$V23) 
abline(coef=c(0,1))
plot(test2$`Bartramia longicauda`, test2$V24) 
abline(coef=c(0,1))
plot(test2$`Bombycilla cedrorum`, test2$V25) 
abline(coef=c(0,1))
plot(test2$`Bonasa umbellus`, test2$V26) 
abline(coef=c(0,1))
plot(test2$`Branta canadensis`, test2$V27) 
abline(coef=c(0,1))
plot(test2$`Bubulcus ibis`, test2$V28) 
abline(coef=c(0,1))
plot(test2$`Buteo jamaicensis`, test2$V29) 
abline(coef=c(0,1))
plot(test2$`Buteo lineatus`, test2$V30) 
abline(coef=c(0,1))
plot(test2$`Buteo platypterus`, test2$V31) 
abline(coef=c(0,1))
plot(test2$`Calamospiza melanocorys`, test2$V32) 
abline(coef=c(0,1))
plot(test2$`Calcarius lapponicus`, test2$V33) 
abline(coef=c(0,1))
plot(test2$`Calcarius pictus`, test2$V34) 
abline(coef=c(0,1))
plot(test2$`Calidris alpina`, test2$V35) 
abline(coef=c(0,1))
plot(test2$`Calidris melanotos`, test2$V36) 
abline(coef=c(0,1))
plot(test2$`Calidris pusilla`, test2$V37) 
abline(coef=c(0,1))
plot(test2$`Callipepla californica`, test2$V38) 
abline(coef=c(0,1))
plot(test2$`Callipepla gambelii`, test2$V39) 
abline(coef=c(0,1))
plot(test2$`Callipepla squamata`, test2$V40) 
abline(coef=c(0,1))
plot(test2$`Calypte anna`, test2$V41) 
abline(coef=c(0,1))
plot(test2$`Campylorhynchus brunneicapillus`, test2$V42) 
abline(coef=c(0,1))
plot(test2$`Cardellina pusilla`, test2$V43) 
abline(coef=c(0,1))
plot(test2$`Cardinalis cardinalis`, test2$V44) 
abline(coef=c(0,1))
plot(test2$`Cardinalis sinuatus`, test2$V45) 
abline(coef=c(0,1))
plot(test2$`Cathartes aura`, test2$V46) 
abline(coef=c(0,1))
plot(test2$`Catharus fuscescens`, test2$V47) 
abline(coef=c(0,1))
plot(test2$`Catharus guttatus`, test2$V48) 
abline(coef=c(0,1))
plot(test2$`Catharus minimus`, test2$V49) 
abline(coef=c(0,1))
plot(test2$`Catharus ustulatus`, test2$V50) 
abline(coef=c(0,1))
plot(test2$`Catherpes mexicanus`, test2$V51) 
abline(coef=c(0,1))
plot(test2$`Certhia americana`, test2$V52) 
abline(coef=c(0,1))
plot(test2$`Chaetura pelagica`, test2$V53) 
abline(coef=c(0,1))
plot(test2$`Chamaea fasciata`, test2$V54) 
abline(coef=c(0,1))
plot(test2$`Charadrius vociferus`, test2$V55) 
abline(coef=c(0,1))
plot(test2$`Chlidonias niger`, test2$V56) 
abline(coef=c(0,1))
plot(test2$`Chondestes grammacus`, test2$V57) 
abline(coef=c(0,1))
plot(test2$`Circus cyaneus`, test2$V58) 
abline(coef=c(0,1))
plot(test2$`Cistothorus palustris`, test2$V59) 
abline(coef=c(0,1))
plot(test2$`Cistothorus platensis`, test2$V60) 
abline(coef=c(0,1))
plot(test2$`Clangula hyemalis`, test2$V61) 
abline(coef=c(0,1))
plot(test2$`Coccyzus americanus`, test2$V62) 
abline(coef=c(0,1))
plot(test2$`Colaptes auratus`, test2$V63) 
abline(coef=c(0,1))
plot(test2$`Colaptes chrysoides`, test2$V64) 
abline(coef=c(0,1))
plot(test2$`Colinus virginianus`, test2$V65) 
abline(coef=c(0,1))
plot(test2$`Columbina passerina`, test2$V66) 
abline(coef=c(0,1))
plot(test2$`Contopus cooperi`, test2$V67) 
abline(coef=c(0,1))
plot(test2$`Contopus sordidulus`, test2$V68) 
abline(coef=c(0,1))
plot(test2$`Contopus virens`, test2$V69) 
abline(coef=c(0,1))
plot(test2$`Corvus brachyrhynchos`, test2$V70) 
abline(coef=c(0,1))
plot(test2$`Corvus corax`, test2$V71) 
abline(coef=c(0,1))
plot(test2$`Corvus cryptoleucus`, test2$V72) 
abline(coef=c(0,1))
plot(test2$`Corvus ossifragus`, test2$V73) 
abline(coef=c(0,1))
plot(test2$`Cyanocitta cristata`, test2$V74) 
abline(coef=c(0,1))
plot(test2$`Cyanocitta stelleri`, test2$V75) 
abline(coef=c(0,1))
plot(test2$`Dolichonyx oryzivorus`, test2$V76) 
abline(coef=c(0,1))
plot(test2$`Dryocopus pileatus`, test2$V77) 
abline(coef=c(0,1))
plot(test2$`Dumetella carolinensis`, test2$V78) 
abline(coef=c(0,1))
plot(test2$`Empidonax alnorum`, test2$V79) 
abline(coef=c(0,1))
plot(test2$`Empidonax difficilis`, test2$V80) 
abline(coef=c(0,1))
plot(test2$`Empidonax hammondii`, test2$V81) 
abline(coef=c(0,1))
plot(test2$`Empidonax minimus`, test2$V82) 
abline(coef=c(0,1))
plot(test2$`Empidonax oberholseri`, test2$V83) 
abline(coef=c(0,1))
plot(test2$`Empidonax occidentalis`, test2$V84) 
abline(coef=c(0,1))
plot(test2$`Empidonax traillii`, test2$V85) 
abline(coef=c(0,1))
plot(test2$`Empidonax virescens`, test2$V86) 
abline(coef=c(0,1))
plot(test2$`Empidonax wrightii`, test2$V87) 
abline(coef=c(0,1))
plot(test2$`Eremophila alpestris`, test2$V88) 
abline(coef=c(0,1))
plot(test2$`Eudocimus albus`, test2$V89) 
abline(coef=c(0,1))
plot(test2$`Euphagus cyanocephalus`, test2$V90) 
abline(coef=c(0,1))
plot(test2$`Falco sparverius`, test2$V91) 
abline(coef=c(0,1))
plot(test2$`Gavia pacifica`, test2$V92) 
abline(coef=c(0,1))
plot(test2$`Geococcyx californianus`, test2$V93) 
abline(coef=c(0,1))
plot(test2$`Geothlypis formosa`, test2$V94) 
abline(coef=c(0,1))
plot(test2$`Geothlypis philadelphia`, test2$V95) 
abline(coef=c(0,1))
plot(test2$`Geothlypis tolmiei`, test2$V96) 
abline(coef=c(0,1))
plot(test2$`Geothlypis trichas`, test2$V97) 
abline(coef=c(0,1))
plot(test2$`Grus canadensis`, test2$V98) 
abline(coef=c(0,1))
plot(test2$`Haemorhous cassinii`, test2$V99) 
abline(coef=c(0,1))
plot(test2$`Haemorhous mexicanus`, test2$V100) 
abline(coef=c(0,1))
plot(test2$`Haemorhous purpureus`, test2$V101) 
abline(coef=c(0,1))
plot(test2$`Helmitheros vermivorum`, test2$V102) 
abline(coef=c(0,1))
plot(test2$`Hirundo rustica`, test2$V103) 
abline(coef=c(0,1))
plot(test2$`Hylocichla mustelina`, test2$V104) 
abline(coef=c(0,1))
plot(test2$`Icteria virens`, test2$V105) 
abline(coef=c(0,1))
plot(test2$`Icterus bullockii`, test2$V106) 
abline(coef=c(0,1))
plot(test2$`Icterus galbula`, test2$V107) 
abline(coef=c(0,1))
plot(test2$`Icterus parisorum`, test2$V108) 
abline(coef=c(0,1))
plot(test2$`Icterus spurius`, test2$V109) 
abline(coef=c(0,1))
plot(test2$`Ixoreus naevius`, test2$V110) 
abline(coef=c(0,1))
plot(test2$`Junco hyemalis`, test2$V111) 
abline(coef=c(0,1))
plot(test2$`Lanius ludovicianus`, test2$V112) 
abline(coef=c(0,1))
plot(test2$`Larus delawarensis`, test2$V113) 
abline(coef=c(0,1))
plot(test2$`Larus hyperboreus`, test2$V114) 
abline(coef=c(0,1))
plot(test2$`Limnothlypis swainsonii`, test2$V115) 
abline(coef=c(0,1))
plot(test2$`Loxia curvirostra`, test2$V116) 
abline(coef=c(0,1))
plot(test2$`Loxia leucoptera`, test2$V117) 
abline(coef=c(0,1))
plot(test2$`Melanerpes carolinus`, test2$V118) 
abline(coef=c(0,1))
plot(test2$`Melanerpes erythrocephalus`, test2$V119) 
abline(coef=c(0,1))
plot(test2$`Melanerpes formicivorus`, test2$V120) 
abline(coef=c(0,1))
plot(test2$`Melanerpes uropygialis`, test2$V121) 
abline(coef=c(0,1))
plot(test2$`Meleagris gallopavo`, test2$V122) 
abline(coef=c(0,1))
plot(test2$`Melospiza georgiana`, test2$V123) 
abline(coef=c(0,1))
plot(test2$`Melospiza lincolnii`, test2$V124) 
abline(coef=c(0,1))
plot(test2$`Melospiza melodia`, test2$V125) 
abline(coef=c(0,1))
plot(test2$`Melozone crissalis`, test2$V126) 
abline(coef=c(0,1))
plot(test2$`Mimus polyglottos`, test2$V127) 
abline(coef=c(0,1))
plot(test2$`Mniotilta varia`, test2$V128) 
abline(coef=c(0,1))
plot(test2$`Molothrus ater`, test2$V129) 
abline(coef=c(0,1))
plot(test2$`Myadestes townsendi`, test2$V130) 
abline(coef=c(0,1))
plot(test2$`Myiarchus cinerascens`, test2$V131) 
abline(coef=c(0,1))
plot(test2$`Myiarchus crinitus`, test2$V132) 
abline(coef=c(0,1))
plot(test2$`Nucifraga columbiana`, test2$V133) 
abline(coef=c(0,1))
plot(test2$`Numenius phaeopus`, test2$V134) 
abline(coef=c(0,1))
plot(test2$`Nycticorax nycticorax`, test2$V135) 
abline(coef=c(0,1))
plot(test2$`Oreoscoptes montanus`, test2$V136) 
abline(coef=c(0,1))
plot(test2$`Parkesia motacilla`, test2$V137) 
abline(coef=c(0,1))
plot(test2$`Passer domesticus`, test2$V138) 
abline(coef=c(0,1))
plot(test2$`Passerculus sandwichensis`, test2$V139) 
abline(coef=c(0,1))
plot(test2$`Passerella iliaca`, test2$V140) 
abline(coef=c(0,1))
plot(test2$`Passerina amoena`, test2$V141) 
abline(coef=c(0,1))
plot(test2$`Passerina caerulea`, test2$V142) 
abline(coef=c(0,1))
plot(test2$`Passerina ciris`, test2$V143) 
abline(coef=c(0,1))
plot(test2$`Passerina cyanea`, test2$V144) 
abline(coef=c(0,1))
plot(test2$`Pelecanus erythrorhynchos`, test2$V145) 
abline(coef=c(0,1))
plot(test2$`Perisoreus canadensis`, test2$V146) 
abline(coef=c(0,1))
plot(test2$`Petrochelidon pyrrhonota`, test2$V147) 
abline(coef=c(0,1))
plot(test2$`Peucaea aestivalis`, test2$V148) 
abline(coef=c(0,1))
plot(test2$`Peucaea botterii`, test2$V149) 
abline(coef=c(0,1))
plot(test2$`Peucaea carpalis`, test2$V150) 
abline(coef=c(0,1))
plot(test2$`Peucaea cassinii`, test2$V151) 
abline(coef=c(0,1))
plot(test2$`Phainopepla nitens`, test2$V152) 
abline(coef=c(0,1))
plot(test2$`Phalacrocorax auritus`, test2$V153) 
abline(coef=c(0,1))
plot(test2$`Phalaropus fulicarius`, test2$V154) 
abline(coef=c(0,1))
plot(test2$`Phalaropus tricolor`, test2$V155) 
abline(coef=c(0,1))
plot(test2$`Phasianus colchicus`, test2$V156) 
abline(coef=c(0,1))
plot(test2$`Pheucticus ludovicianus`, test2$V157) 
abline(coef=c(0,1))
plot(test2$`Pheucticus melanocephalus`, test2$V158) 
abline(coef=c(0,1))
plot(test2$`Pica hudsonia`, test2$V159) 
abline(coef=c(0,1))
plot(test2$`Picoides albolarvatus`, test2$V160) 
abline(coef=c(0,1))
plot(test2$`Picoides nuttallii`, test2$V161) 
abline(coef=c(0,1))
plot(test2$`Picoides scalaris`, test2$V162) 
abline(coef=c(0,1))
plot(test2$`Picoides villosus`, test2$V163) 
abline(coef=c(0,1))
plot(test2$`Pinicola enucleator`, test2$V164) 
abline(coef=c(0,1))
plot(test2$`Pipilo chlorurus`, test2$V165) 
abline(coef=c(0,1))
plot(test2$`Pipilo erythrophthalmus`, test2$V166) 
abline(coef=c(0,1))
plot(test2$`Pipilo maculatus`, test2$V167) 
abline(coef=c(0,1))
plot(test2$`Piranga ludoviciana`, test2$V168) 
abline(coef=c(0,1))
plot(test2$`Piranga olivacea`, test2$V169) 
abline(coef=c(0,1))
plot(test2$`Piranga rubra`, test2$V170) 
abline(coef=c(0,1))
plot(test2$`Plectrophenax nivalis`, test2$V171) 
abline(coef=c(0,1))
plot(test2$`Pluvialis dominica`, test2$V172) 
abline(coef=c(0,1))
plot(test2$`Poecile atricapillus`, test2$V173) 
abline(coef=c(0,1))
plot(test2$`Poecile gambeli`, test2$V174) 
abline(coef=c(0,1))
plot(test2$`Poecile hudsonicus`, test2$V175) 
abline(coef=c(0,1))
plot(test2$`Polioptila caerulea`, test2$V176) 
abline(coef=c(0,1))
plot(test2$`Polioptila melanura`, test2$V177) 
abline(coef=c(0,1))
plot(test2$`Porzana carolina`, test2$V178) 
abline(coef=c(0,1))
plot(test2$`Progne subis`, test2$V179) 
abline(coef=c(0,1))
plot(test2$`Protonotaria citrea`, test2$V180) 
abline(coef=c(0,1))
plot(test2$`Psaltriparus minimus`, test2$V181) 
abline(coef=c(0,1))
plot(test2$`Pyrocephalus rubinus`, test2$V182) 
abline(coef=c(0,1))
plot(test2$`Quiscalus major`, test2$V183) 
abline(coef=c(0,1))
plot(test2$`Quiscalus quiscula`, test2$V184) 
abline(coef=c(0,1))
plot(test2$`Rallus limicola`, test2$V185) 
abline(coef=c(0,1))
plot(test2$`Regulus calendula`, test2$V186) 
abline(coef=c(0,1))
plot(test2$`Regulus satrapa`, test2$V187) 
abline(coef=c(0,1))
plot(test2$`Sayornis nigricans`, test2$V188) 
abline(coef=c(0,1))
plot(test2$`Sayornis phoebe`, test2$V189) 
abline(coef=c(0,1))
plot(test2$`Seiurus aurocapilla`, test2$V190) 
abline(coef=c(0,1))
plot(test2$`Selasphorus platycercus`, test2$V191) 
abline(coef=c(0,1))
plot(test2$`Selasphorus rufus`, test2$V192) 
abline(coef=c(0,1))
plot(test2$`Setophaga caerulescens`, test2$V193) 
abline(coef=c(0,1))
plot(test2$`Setophaga citrina`, test2$V194) 
abline(coef=c(0,1))
plot(test2$`Setophaga coronata`, test2$V195) 
abline(coef=c(0,1))
plot(test2$`Setophaga discolor`, test2$V196) 
abline(coef=c(0,1))
plot(test2$`Setophaga dominica`, test2$V197) 
abline(coef=c(0,1))
plot(test2$`Setophaga fusca`, test2$V198) 
abline(coef=c(0,1))
plot(test2$`Setophaga magnolia`, test2$V199) 
abline(coef=c(0,1))
plot(test2$`Setophaga nigrescens`, test2$V200) 
abline(coef=c(0,1))
plot(test2$`Setophaga occidentalis`, test2$V201) 
abline(coef=c(0,1))
plot(test2$`Setophaga pensylvanica`, test2$V202) 
abline(coef=c(0,1))
plot(test2$`Setophaga petechia`, test2$V203) 
abline(coef=c(0,1))
plot(test2$`Setophaga pinus`, test2$V204) 
abline(coef=c(0,1))
plot(test2$`Setophaga ruticilla`, test2$V205) 
abline(coef=c(0,1))
plot(test2$`Setophaga striata`, test2$V206) 
abline(coef=c(0,1))
plot(test2$`Setophaga virens`, test2$V207) 
abline(coef=c(0,1))
plot(test2$`Sialia currucoides`, test2$V208) 
abline(coef=c(0,1))
plot(test2$`Sialia mexicana`, test2$V209) 
abline(coef=c(0,1))
plot(test2$`Sialia sialis`, test2$V210) 
abline(coef=c(0,1))
plot(test2$`Sitta canadensis`, test2$V211) 
abline(coef=c(0,1))
plot(test2$`Sitta carolinensis`, test2$V212) 
abline(coef=c(0,1))
plot(test2$`Sitta pusilla`, test2$V213) 
abline(coef=c(0,1))
plot(test2$`Sitta pygmaea`, test2$V214) 
abline(coef=c(0,1))
plot(test2$`Sphyrapicus ruber`, test2$V215) 
abline(coef=c(0,1))
plot(test2$`Sphyrapicus varius`, test2$V216) 
abline(coef=c(0,1))
plot(test2$`Spinus lawrencei`, test2$V217) 
abline(coef=c(0,1))
plot(test2$`Spinus pinus`, test2$V218) 
abline(coef=c(0,1))
plot(test2$`Spinus psaltria`, test2$V219) 
abline(coef=c(0,1))
plot(test2$`Spinus tristis`, test2$V220) 
abline(coef=c(0,1))
plot(test2$`Spiza americana`, test2$V221) 
abline(coef=c(0,1))
plot(test2$`Spizella breweri`, test2$V222) 
abline(coef=c(0,1))
plot(test2$`Spizella pallida`, test2$V223) 
abline(coef=c(0,1))
plot(test2$`Spizella passerina`, test2$V224) 
abline(coef=c(0,1))
plot(test2$`Spizella pusilla`, test2$V225) 
abline(coef=c(0,1))
plot(test2$`Spizelloides arborea`, test2$V226) 
abline(coef=c(0,1))
plot(test2$`Stercorarius longicaudus`, test2$V227) 
abline(coef=c(0,1))
plot(test2$`Stercorarius parasiticus`, test2$V228) 
abline(coef=c(0,1))
plot(test2$`Sturnella magna`, test2$V229) 
abline(coef=c(0,1))
plot(test2$`Sturnella neglecta`, test2$V230) 
abline(coef=c(0,1))
plot(test2$`Sturnus vulgaris`, test2$V231) 
abline(coef=c(0,1))
plot(test2$`Tachycineta bicolor`, test2$V232) 
abline(coef=c(0,1))
plot(test2$`Tachycineta thalassina`, test2$V233) 
abline(coef=c(0,1))
plot(test2$`Thryomanes bewickii`, test2$V234) 
abline(coef=c(0,1))
plot(test2$`Thryothorus ludovicianus`, test2$V235) 
abline(coef=c(0,1))
plot(test2$`Toxostoma crissale`, test2$V236) 
abline(coef=c(0,1))
plot(test2$`Toxostoma curvirostre`, test2$V237) 
abline(coef=c(0,1))
plot(test2$`Toxostoma rufum`, test2$V238) 
abline(coef=c(0,1))
plot(test2$`Troglodytes aedon`, test2$V239) 
abline(coef=c(0,1))
plot(test2$`Turdus migratorius`, test2$V240) 
abline(coef=c(0,1))
plot(test2$`Tyrannus forficatus`, test2$V241) 
abline(coef=c(0,1))
plot(test2$`Tyrannus tyrannus`, test2$V242) 
abline(coef=c(0,1))
plot(test2$`Tyrannus verticalis`, test2$V243) 
abline(coef=c(0,1))
plot(test2$`Tyrannus vociferans`, test2$V244) 
abline(coef=c(0,1))
plot(test2$`Vireo bellii`, test2$V245) 
abline(coef=c(0,1))
plot(test2$`Vireo cassinii`, test2$V246) 
abline(coef=c(0,1))
plot(test2$`Vireo flavifrons`, test2$V247) 
abline(coef=c(0,1))
plot(test2$`Vireo gilvus`, test2$V248) 
abline(coef=c(0,1))
plot(test2$`Vireo griseus`, test2$V249) 
abline(coef=c(0,1))
plot(test2$`Vireo huttoni`, test2$V250) 
abline(coef=c(0,1))
plot(test2$`Vireo olivaceus`, test2$V251) 
abline(coef=c(0,1))
plot(test2$`Vireo plumbeus`, test2$V252) 
abline(coef=c(0,1))
plot(test2$`Vireo solitarius`, test2$V253) 
abline(coef=c(0,1))
plot(test2$`Vireo vicinior`, test2$V254) 
abline(coef=c(0,1))
plot(test2$`Xanthocephalus xanthocephalus`, test2$V255) 
abline(coef=c(0,1))
plot(test2$`Zenaida asiatica`, test2$V256) 
abline(coef=c(0,1))
plot(test2$`Zenaida macroura`, test2$V257) 
abline(coef=c(0,1))
plot(test2$`Zonotrichia albicollis`, test2$V258) 
abline(coef=c(0,1))
plot(test2$`Zonotrichia atricapilla`, test2$V259) 
abline(coef=c(0,1))
plot(test2$`Zonotrichia leucophrys`, test2$V260) 
abline(coef=c(0,1))

